name: Build Next Preview

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-js-env

      - name: Build
        run: pnpm build --mode stage
        env:
          VITE_TURNSTILE_SITE_KEY: '0x4AAAAAAAAu7JMNAS8r2xDe'

      - name: upload website build artifact
        uses: actions/upload-artifact@v3
        with:
          name: sites-next
          path: packages/website/dist
